### ISSUE TITLE
Clobbering UIBackgroundModes can be destructive for other plugins

### ISSUE THREAD

**Issue by keekerdc** [EddyVerbruggen/cordova-plugin-backgroundaudio#1]
https://github.com/EddyVerbruggen/cordova-plugin-backgroundaudio/blob/master/plugin.xml#L21

OK, so Cordova build is a bit ham-fisted when it comes to managing this part of the plist.  The workaround here causes a different issue if multiple plugins are trying to write to this array.

I have another plugin that needs 'background fetch' activated, and it means I have to go back in and re-check this option every time I build.

There's gotta be a better way here; simply including a note in your readme as to how to make this happen in XCode is probably a better route, I think.

**Comment by EddyVerbruggen** [comment]
Hi @keekerdc thanks for reminding me about this issue. This hacky workaround no longer seems required with newer versions of Cordova (according to this issue: https://issues.apache.org/jira/browse/CB-4731).

So I think I'll remove the CLOBBERS thingy now. Would you be so kind to confirm it works with the new 1.0.1 version?

**Comment by keekerdc** [comment]
Right on.  I won't have time until the weekend but I certainly will give it a spin.  Thanks!

**Comment by keekerdc** [comment]
Sorry for my delayed response on this.  All seems well with this change.  Thanks!

**Comment by mdumouchel** [comment]
Hmmm, I'm using Cordova 6.2.0 and still had this issue.
