### ISSUE TITLE
App gets rejected

### ISSUE THREAD

**Issue by vandres** [EddyVerbruggen/cordova-plugin-backgroundaudio#3]
Hi, my App gets rejected when using your Plugin. See details below. I now tried to use your plugin without the background mode for audio and it seems to work anyway. I resubmitted it to the app store and are now waiting for the review.

Is this perhaps something for the readme or will the plugin stop working under certain circumstances?

---

2.16 Details

Your app declares support for audio in the UIBackgroundModes key in your Info.plist, but we were unable to play any audible content when the application was running in the background.

Next Steps

The audio key is intended for use by applications that provide audible content to the user while in the background, such as music player or streaming audio applications. Please revise your app to provide audible content to the user while the app is in the background or remove the "audio" setting from the UIBackgroundModes key.

Resources

If you have difficulty reproducing a reported issue, please try testing the workflow described in Technical Q&A QA1764: How to reproduce bugs reported against App Store submissions.

If you have code-level questions after utilizing the above resources, you may wish to consult with Apple Developer Technical Support. When the DTS engineer follows up with you, please be ready to provide:
- complete details of your rejection issue(s)
- screenshots
- steps to reproduce the issue(s)
- symbolicated crash logs - if your issue results in a crash log

**Comment by EddyVerbruggen** [comment]
You didn't tell what your app does or tries to do - Apple tried to play audio but:
- couldn't find a way to do it, OR
- played audio and it stopped when the app was put in the background

I'm not sure which scenario applies..

**Comment by vandres** [comment]
Sorry. He is some more information.

Our app plays videos in the WebView. When the Apple Smartphone is muted by tha hardware button, videos don't play any sound. So the media is muted by the ringtone. With your plugin our videos also play, when the ringtone is muted. This works for us, even when the background mode is removed from config.

If we try to submit the app to the app store with the background mode configured, it gets rejected. The reviewer doesn't see the need for the background mode (probably in the Objectiive-C code). Can you confirm, that we don't need it for our scenario?

**Comment by EddyVerbruggen** [comment]
Seems like you've confirmed that yourself, right?

Apple allows background audio permission ONLY when you really play audio when the app is in the background.

**Comment by vandres** [comment]
Ok. So it would be nice to mention it to other users who install your plugin, because of the use case we have. We found your plugin, because of a Stackoverflow question regarding that

**Comment by EddyVerbruggen** [comment]
If you feel that a mention in the readme would be justified then please go ahead and send me a PR.
