### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Heshyo** [EddyVerbruggen/cordova-plugin-backgroundaudio#5]
I'm using the following configuration on Phonegap Build, but still whenever I click the home button, the stream I'm playing fades out. Any idea why?

```
<plugin name="cordova-plugin-media" source="npm" />
<plugin spec="https://github.com/EddyVerbruggen/cordova-plugin-backgroundaudio.git#1.0.1" />
```

**Comment by EddyVerbruggen** [comment]
Nope I don't know why as I don't currently use it. Anyone?

**Comment by ihadeed** [comment]
@EddyVerbruggen I came here to ask if the plugin is functional. Also, are you planning on adding Android support?

Thanks :grin:

**Comment by Heshyo** [comment]
@ihadeed On Andoid the media continues to play after clicking the home button, switching to other apps (maybe not apps that would also require sound?), and even locking the phone, but I don't know for how long, also if you open other apps your app may be closed.

Maybe you'd want to check https://github.com/katzer/cordova-plugin-background-mode but for Android only, as publishing this for iOS is probably not possible.

EDIT: well actually that other plugin may be allowed on the store as long as you indeed need to play audio on the background.

**Comment by ihadeed** [comment]
@Heshyo Thanks I will test them out.

I'm trying to create a special music player in Cordova, and I was thinking to have it running in the background somehow, and display a persistent control (as a notification) somehow. 

These two plugins seem like a good starting point.

**Comment by Heshyo** [comment]
@ihadeed I tries the https://github.com/katzer/cordova-plugin-background-mode plugin, but somehow it didn't work. I'll try to look more into it once I have time. Please report here if you have any luck.

**Comment by ihadeed** [comment]
Thank you for the update!

**Comment by Heshyo** [comment]
@ihadeed Did you have any luck with playing audio in the background?

@EddyVerbruggen What does it take for a plugin to become a "Telerik verified plugin"? Does it depend on the popularity, or when you actually have time to test it thoroughly?

**Comment by EddyVerbruggen** [comment]
@Heshyo We won't add everything because that's impossible, so it's mostly demand driven. And since I'm a one-man army doing it part-time there's also a limit on the amount of work we can do.

**Comment by Heshyo** [comment]
@EddyVerbruggen OK thanks, I know you're pretty busy with all those plugins you maintain. Thanks again for your dedication.
